### ISSUE TITLE
Support arduino Uno?

### ISSUE THREAD

**Issue by geologic** [andresoliva/LoRa-E5#2]
Hi

I'm trying your library with arduino Uno but i get the following error at compilation:

(...)LoRa-E5.h:63:31: error: 'UART' does not name a type; did you mean 'UDR0'?

To use softwareSerial with Uno or Serial1 on a custom board (328PB) what do i need to modify?

Thanks

**Comment by andresoliva** [comment]
Hello Geologic, . I am in a process to move myself to Italy so I am a little busy at this time.
